import numpy as np
x = np.array([1,2,2.5])
print(x)
print(x.dtype)
x = x.astype('float64')
print(x)
print(x.dtype)
y = np.array([0.3,5,0],dtype='S32')
print(y)
print(y.dtype)
y = y.astype('float64')
# print(y)
# print(y.dtype)
print(x - y)